language: perl6
perl6:
  - latest
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "Please disable builds on branch updates in settings."; travis_terminate 0; fi

install:
  - rakudobrew build zef

script:
  - zef install IO::Socket::SSL
  - zef install Test::META LWP::Simple
  - perl6 ./.travis/testpackagemeta.pl
